# Generated by Django 5.2.13 on 2026-05-05 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nova_solicitacao_matricula', '📥 Nova solicitação de matrícula'), ('nova_solicitacao_cancelamento', '⚠️ Nova solicitação de cancelamento'), ('aluno_entrou_fila', '⏳ Aluno entrou na fila de espera'), ('vaga_aberta_com_fila', '🎯 Vaga aberta — chamar fila'), ('aluno_pagou', '💰 Pagamento recebido'), ('estoque_baixo', '📦 Estoque baixo'), ('outros', '🔔 Outros')], max_length=40)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(blank=True, help_text='Se vazio, vai para todos os admins', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação de Admin',
                'verbose_name_plural': 'Notificações de Admin',
                'ordering': ['-criada_em'],
            },
        ),
    ]
