# Generated by Django 5.2.13 on 2026-07-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_arena_matricula_arena_plano_arena_quadra_arena'),
        ('notificacoes', '0002_notificacaoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='notificacaoadmin',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_admin_arena', to='arena.arena'),
        ),
    ]
