import { useEffect, useState } from 'react';
import api from '../../api/client';
import Modal from '../../components/Modal';

const ROLE_LABELS = { dono: 'Proprietario', administrador: 'Administrador', recepcao: 'Recepcao', financeiro: 'Financeiro', professor: 'Professor', estoque: 'Estoque' };

function Equipe() {
  const [users, setUsers] = useState([]); const [invitations, setInvitations] = useState([]);
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ email: '', role: 'administrador' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { try { const [u, i] = await Promise.all([api.get('/admin/team/users/'), api.get('/admin/team/invitations/')]); setUsers(u.data.results || u.data); setInvitations(i.data.results || i.data); } catch (err) { setError(err.response?.data?.detail || 'Nao foi possivel carregar a equipe.'); } }
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, []);
  async function invite(event) { event.preventDefault(); setBusy(true); setError(''); try { await api.post('/admin/team/invitations/', form); setOpen(false); setForm({ email: '', role: 'administrador' }); await load(); } catch (err) { setError(err.response?.data?.detail || 'Nao foi possivel enviar o convite.'); } finally { setBusy(false); } }
  async function action(path, confirmation) { if (confirmation && !window.confirm(confirmation)) return; setBusy(true); setError(''); try { await api.post(path); await load(); } catch (err) { setError(err.response?.data?.detail || 'A operacao nao foi concluida.'); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="muted-label">Acessos da arena</p><h1 className="text-3xl font-bold">Equipe e permissoes</h1></div><button type="button" onClick={() => setOpen(true)} className="btn-primary">Convidar usuario</button></header>{error && <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}
    <section className="app-surface overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-bold">Usuarios</h2></div>{users.length === 0 ? <p className="p-8 text-center text-slate-500">Nenhum usuario administrativo.</p> : <div className="divide-y">{users.map((user) => <article key={user.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><h3 className="font-bold">{user.nome}</h3><p className="text-sm text-slate-500">{user.email} · {ROLE_LABELS[user.papel] || user.papel}</p><p className={`mt-1 text-xs font-bold ${user.is_active ? 'text-emerald-700' : 'text-red-700'}`}>{user.is_active ? 'Ativo' : 'Desativado'}</p></div><div className="flex flex-wrap gap-2">{user.papel !== 'dono' && user.is_active && <><button type="button" disabled={busy} onClick={() => action(`/admin/team/users/${user.id}/transfer_ownership/`, `Transferir a propriedade para ${user.nome}?`)} className="btn-secondary">Tornar proprietario</button><button type="button" disabled={busy} onClick={() => action(`/admin/team/users/${user.id}/deactivate/`, `Desativar ${user.nome}?`)} className="btn-secondary text-red-700">Desativar</button></>}</div></article>)}</div>}</section>
    <section className="app-surface overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-bold">Convites</h2></div>{invitations.length === 0 ? <p className="p-8 text-center text-slate-500">Nenhum convite enviado.</p> : <div className="divide-y">{invitations.map((item) => <div key={item.public_id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="font-bold">{item.email}</p><p className="text-sm text-slate-500">{ROLE_LABELS[item.role]} · {item.status}</p></div>{item.status === 'pending' && <div className="flex gap-2"><button type="button" onClick={() => action(`/admin/team/invitations/${item.public_id}/resend/`)} className="btn-secondary">Reenviar</button><button type="button" onClick={() => action(`/admin/team/invitations/${item.public_id}/cancel/`)} className="btn-secondary text-red-700">Cancelar</button></div>}</div>)}</div>}</section>
    <Modal aberto={open} onFechar={() => setOpen(false)} titulo="Convidar para a equipe"><form onSubmit={invite} className="space-y-4"><label className="block"><span className="mb-1 block text-sm font-bold">E-mail</span><input autoFocus type="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="input-field w-full" /></label><label className="block"><span className="mb-1 block text-sm font-bold">Perfil</span><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} className="input-field w-full">{['administrador', 'recepcao', 'financeiro', 'professor', 'estoque'].map((role) => <option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select></label><button type="submit" disabled={busy} className="btn-primary w-full">{busy ? 'Enviando...' : 'Enviar convite'}</button></form></Modal>
  </div>;
}
export default Equipe;

