import { useEffect, useState } from 'react';
import api from '../../api/client';
import Modal from '../../components/Modal';

function Suporte() {
  const [tickets, setTickets] = useState([]); const [selected, setSelected] = useState(null); const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ subject: '', category: 'technical', priority: 'normal' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { try { const response = await api.get('/support/tickets/'); setTickets(response.data.results || response.data); } catch (err) { setError(err.response?.data?.detail || 'Nao foi possivel carregar os chamados.'); } }
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, []);
  async function create(event) { event.preventDefault(); setBusy(true); try { await api.post('/support/tickets/', form); setOpen(false); setForm({ subject: '', category: 'technical', priority: 'normal' }); await load(); } catch (err) { setError(err.response?.data?.detail || 'Nao foi possivel abrir o chamado.'); } finally { setBusy(false); } }
  async function sendMessage() { if (!message.trim()) return; setBusy(true); try { const response = await api.post(`/support/tickets/${selected.id}/messages/`, { body: message }); setSelected(response.data); setMessage(''); await load(); } catch (err) { setError(err.response?.data?.detail || 'Nao foi possivel enviar a mensagem.'); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-6xl space-y-6"><header className="flex items-end justify-between"><div><p className="muted-label">Atendimento</p><h1 className="text-3xl font-bold">Suporte</h1></div><button onClick={() => setOpen(true)} className="btn-primary">Novo chamado</button></header>{error && <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}
    <div className="grid gap-5 lg:grid-cols-[1fr_1.4fr]"><section className="app-surface overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Chamados</h2></div>{tickets.length === 0 ? <p className="p-8 text-center text-slate-500">Nenhum chamado aberto.</p> : <div className="divide-y">{tickets.map((ticket) => <button type="button" key={ticket.id} onClick={() => setSelected(ticket)} className={`block w-full p-5 text-left ${selected?.id === ticket.id ? 'bg-teal-50' : 'hover:bg-slate-50'}`}><div className="flex justify-between"><strong>#{ticket.id} {ticket.subject}</strong><span className="text-xs uppercase text-slate-500">{ticket.status}</span></div><p className="mt-1 text-sm text-slate-500">{ticket.arena_name} · {ticket.priority}</p></button>)}</div>}</section>
      <section className="app-surface min-h-96 p-6">{!selected ? <p className="text-center text-slate-500">Selecione um chamado para acompanhar.</p> : <><div className="border-b pb-4"><h2 className="text-xl font-bold">#{selected.id} {selected.subject}</h2><p className="mt-1 text-sm text-slate-500">SLA: {selected.sla_due_at ? new Date(selected.sla_due_at).toLocaleString('pt-BR') : '-'}</p></div><div className="my-5 space-y-3">{selected.messages?.map((item) => <div key={item.id} className="rounded-lg bg-slate-50 p-4"><div className="flex justify-between text-xs text-slate-500"><strong>{item.author_name}</strong><span>{new Date(item.created_at).toLocaleString('pt-BR')}</span></div><p className="mt-2 whitespace-pre-wrap text-sm">{item.body}</p></div>)}</div><textarea value={message} onChange={(event) => setMessage(event.target.value)} className="input-field min-h-24 w-full" placeholder="Escreva uma mensagem" /><button disabled={busy} onClick={sendMessage} className="btn-primary mt-3">Enviar mensagem</button></>}</section></div>
    <Modal aberto={open} onFechar={() => setOpen(false)} titulo="Novo chamado"><form onSubmit={create} className="space-y-4"><Field label="Assunto" value={form.subject} onChange={(value) => setForm({ ...form, subject: value })} /><Select label="Categoria" value={form.category} onChange={(value) => setForm({ ...form, category: value })} options={['technical', 'billing', 'onboarding', 'other']} /><Select label="Prioridade" value={form.priority} onChange={(value) => setForm({ ...form, priority: value })} options={['low', 'normal', 'high', 'urgent']} /><button disabled={busy} className="btn-primary w-full">Abrir chamado</button></form></Modal>
  </div>;
}
function Field({ label, value, onChange }) { return <label className="block"><span className="mb-1 block text-sm font-bold">{label}</span><input required value={value} onChange={(event) => onChange(event.target.value)} className="input-field w-full" /></label>; }
function Select({ label, value, onChange, options }) { return <label className="block"><span className="mb-1 block text-sm font-bold">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="input-field w-full">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
export default Suporte;

