# Generated by Django 5.2.13 on 2026-07-23 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='canal',
            field=models.CharField(choices=[('app', 'App'), ('balcao', 'Balcao'), ('ambos', 'App e balcao')], default='app', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('venda_balcao', 'Venda de balcao'), ('venda_app', 'Venda pelo app'), ('ajuste', 'Ajuste'), ('perda', 'Perda'), ('devolucao', 'Devolucao')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('estoque_antes', models.PositiveIntegerField()),
                ('estoque_depois', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='loja.produto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
