# Generated by Django 5.2.13 on 2026-07-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_arena_matricula_arena_plano_arena_quadra_arena'),
        ('loja', '0003_fornecedor_movimentacaoestoque_custo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_loja', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_estoque', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='produto',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='venda',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='arena.arena'),
        ),
    ]
