# Generated by Django 5.2.13 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_arena_matricula_arena_plano_arena_quadra_arena'),
        ('loja', '0004_categoria_arena_fornecedor_arena_loteestoque_arena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False), models.Q(('sku', ''), _negated=True)), fields=('arena', 'sku'), name='uniq_produto_sku_por_arena'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False), models.Q(('codigo_barras', ''), _negated=True)), fields=('arena', 'codigo_barras'), name='uniq_produto_codigo_barras_por_arena'),
        ),
    ]
