# Generated by Django 5.2.13 on 2026-07-30 14:20

import common_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_produto_codigo_barras_alter_produto_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', validators=[common_validators.validate_image_upload]),
        ),
    ]
