# Generated by Django 5.2.13 on 2026-08-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0009_require_arena_on_payment_webhook_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaasPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('grace_days', models.PositiveSmallIntegerField(default=7)),
                ('max_admins', models.PositiveIntegerField(default=3)),
                ('max_professors', models.PositiveIntegerField(default=10)),
                ('max_students', models.PositiveIntegerField(default=150)),
                ('max_courts', models.PositiveIntegerField(default=4)),
                ('storage_mb', models.PositiveIntegerField(default=512)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['monthly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SaasSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=10)),
                ('pending_billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Mensal'), ('annual', 'Anual')], max_length=10)),
                ('status', models.CharField(choices=[('trialing', 'Em teste'), ('active', 'Ativa'), ('past_due', 'Em atraso'), ('suspended', 'Suspensa'), ('cancel_at_period_end', 'Cancela ao fim do ciclo'), ('canceled', 'Cancelada')], db_index=True, default='trialing', max_length=30)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='mercado_pago', max_length=40)),
                ('provider_preapproval_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('provider_payer_id', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arena', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_subscription', to='arena.arena')),
                ('pending_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_subscriptions', to='saas_billing.saasplan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='saas_billing.saasplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaasInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('subscription', 'Assinatura'), ('upgrade', 'Upgrade'), ('adjustment', 'Ajuste')], default='subscription', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga'), ('failed', 'Falhou'), ('canceled', 'Cancelada'), ('refunded', 'Estornada')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(db_index=True, max_length=160, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('provider_checkout_id', models.CharField(blank=True, max_length=160)),
                ('checkout_url', models.URLField(blank=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_invoices', to='arena.arena')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='saas_billing.saassubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaasWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mercado_pago', max_length=40)),
                ('event_id', models.CharField(max_length=180)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('signature_valid', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('arena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saas_webhook_events', to='arena.arena')),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_saas_provider_event')],
            },
        ),
    ]
