# Generated by Django 5.2.13 on 2026-04-28 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias_semana', models.CharField(help_text='Ex: seg,qua,sex', max_length=50)),
                ('horario', models.TimeField()),
                ('vagas', models.PositiveSmallIntegerField(default=8)),
                ('ativa', models.BooleanField(default=True)),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'aluno'}, related_name='turmas', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'professor'}, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.quadra')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField(default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='aulas.turma')),
            ],
            options={
                'ordering': ['-data', '-horario'],
                'unique_together': {('aluno', 'turma', 'data')},
            },
        ),
    ]
