# Generated by Django 5.2.13 on 2026-05-05 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matricula', 'Solicitação de Matrícula'), ('cancelamento', 'Solicitação de Cancelamento')], default='matricula', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada pelo aluno')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('observacao_aluno', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_respondidas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='aulas.turma')),
            ],
            options={
                'verbose_name': 'Solicitação de Matrícula',
                'verbose_name_plural': 'Solicitações de Matrícula',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('matriculado', 'Matriculado (saiu da fila)'), ('desistiu', 'Desistiu')], default='aguardando', max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_chamada', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_espera', to=settings.AUTH_USER_MODEL)),
                ('chamado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_chamadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_espera', to='aulas.turma')),
            ],
            options={
                'verbose_name': 'Fila de Espera',
                'verbose_name_plural': 'Filas de Espera',
                'ordering': ['turma', 'posicao'],
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
