# Generated by Django 5.2.13 on 2026-07-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_arena_matricula_arena_plano_arena_quadra_arena'),
        ('aulas', '0002_solicitacaomatricula_filaespera'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='filaespera',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filas_espera', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='solicitacaomatricula',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_matricula', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='turma',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='arena.arena'),
        ),
    ]
