# Generated by Django 5.2.13 on 2026-08-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0010_arenaonboarding_arenabusinesshours_modalidade'),
        ('aulas', '0004_require_arena_on_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='arena.modalidade'),
        ),
    ]
