# Generated by Django 5.2.13 on 2026-08-11 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0011_arena_checkin_minutes_after_and_more'),
        ('aulas', '0006_backfill_modalidade_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='inadimplente_no_momento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkin',
            name='motivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='checkin',
            name='origem',
            field=models.CharField(choices=[('mobile', 'Aplicativo mobile'), ('manual', 'Registro manual'), ('legacy', 'Registro legado')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='solicitado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando validacao'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado'), ('absent', 'Ausente')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AulaOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(db_index=True)),
                ('horario_previsto', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('canceled', 'Cancelada')], db_index=True, default='scheduled', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_ocorrencias', to='arena.arena')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='aulas.turma')),
            ],
            options={
                'ordering': ['data', 'horario_previsto'],
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='aulas.aulaocorrencia'),
        ),
        migrations.AddConstraint(
            model_name='aulaocorrencia',
            constraint=models.UniqueConstraint(fields=('turma', 'data'), name='unique_aula_ocorrencia_turma_data'),
        ),
    ]
