# Generated by Django 5.2.13 on 2026-07-29 16:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0003_arena_matricula_arena_plano_arena_quadra_arena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receber', 'A receber'), ('pagar', 'A pagar')], max_length=20)),
                ('descricao', models.CharField(max_length=160)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('fornecedor', models.CharField(blank=True, max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_financeiras', to='arena.arena')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vencimento', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ContratoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('ip_aceite', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='arena.arena')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='arena.matricula')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('modalidade_interesse', models.CharField(blank=True, max_length=80)),
                ('origem', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicacao'), ('balcao', 'Balcao'), ('site', 'Site'), ('outro', 'Outro')], default='whatsapp', max_length=20)),
                ('etapa', models.CharField(choices=[('novo', 'Novo'), ('contato', 'Em contato'), ('experimental', 'Aula experimental'), ('negociacao', 'Negociacao'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('valor_potencial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('proximo_contato', models.DateField(blank=True, null=True)),
                ('motivo_perda', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='arena.arena')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proximo_contato', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReservaQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('cliente_telefone', models.CharField(blank=True, max_length=30)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_quadra', to=settings.AUTH_USER_MODEL)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_quadra', to='arena.arena')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_criadas', to=settings.AUTH_USER_MODEL)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='arena.quadra')),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('arena', 'quadra', 'data', 'hora_inicio', 'hora_fim'), name='uniq_reserva_horario_por_quadra')],
            },
        ),
    ]
