# Generated by Django 5.2.13 on 2026-07-30 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_arena_matricula_arena_plano_arena_quadra_arena'),
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80)),
                ('entidade_tipo', models.CharField(max_length=80)),
                ('entidade_id', models.CharField(blank=True, max_length=80)),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_novos', models.JSONField(blank=True, default=dict)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='arena.arena')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(max_length=160)),
                ('categoria', models.CharField(choices=[('evento', 'Evento'), ('chuva', 'Chuva'), ('manutencao', 'Manutencao'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_quadra', to='arena.arena')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='arena.quadra')),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FaixaPrecoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativa', models.BooleanField(default=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_preco_reserva', to='arena.arena')),
                ('quadra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faixas_preco', to='arena.quadra')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fim'))), name='faixa_preco_hora_inicio_lt_fim')],
            },
        ),
    ]
