# Generated by Django 5.2.13 on 2026-08-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0009_require_arena_on_payment_webhook_event'),
        ('gestao', '0002_auditlog_bloqueioquadra_faixaprecoreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='arena.arena'),
        ),
    ]
