# Generated by Django 5.2.13 on 2026-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='mercado_pago_checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='mercado_pago_payment_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='mercado_pago_preference_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
