# Generated by Django 5.2.13 on 2026-07-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_mensalidade_external_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='arenas/logos/')),
                ('cor_primaria', models.CharField(default='#0F766E', max_length=20)),
                ('cor_secundaria', models.CharField(default='#111827', max_length=20)),
                ('cor_fundo', models.CharField(default='#f9fafb', max_length=20)),
                ('cor_texto', models.CharField(default='#111827', max_length=20)),
                ('dominio', models.CharField(blank=True, max_length=120)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='plano',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='arena.arena'),
        ),
        migrations.AddField(
            model_name='quadra',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quadras', to='arena.arena'),
        ),
    ]
