# Generated by Django 5.2.13 on 2026-07-30 14:20

import common_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_arena_matricula_arena_plano_arena_quadra_arena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='arenas/logos/', validators=[common_validators.validate_image_upload]),
        ),
    ]
