# Generated by Django 5.2.13 on 2026-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_alter_arena_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='external_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arena',
            name='cor_primaria',
            field=models.CharField(default='#123B5D', max_length=20),
        ),
        migrations.AlterField(
            model_name='arena',
            name='cor_secundaria',
            field=models.CharField(default='#22C55E', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('provider', 'external_id')},
            },
        ),
    ]
