# Generated by Django 5.2.13 on 2026-08-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0009_require_arena_on_payment_webhook_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('identification', 'Identificacao'), ('hours', 'Horarios'), ('courts', 'Quadras'), ('modalities', 'Modalidades'), ('professors', 'Professores'), ('students', 'Alunos'), ('review', 'Revisao')], default='identification', max_length=30)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('arena', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='arena.arena')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')])),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='arena.arena')),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('arena', 'weekday'), name='unique_business_hours_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cor', models.CharField(default='#0F766E', max_length=7)),
                ('ativa', models.BooleanField(default=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='arena.arena')),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('arena', 'nome'), name='unique_modalidade_name_per_arena')],
            },
        ),
    ]
