# Generated by Django 5.2.13 on 2026-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0010_arenaonboarding_arenabusinesshours_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='checkin_minutes_after',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='arena',
            name='checkin_minutes_before',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='arena',
            name='delinquent_checkin_policy',
            field=models.CharField(choices=[('allow_with_warning', 'Permitir com alerta'), ('block', 'Bloquear')], default='allow_with_warning', max_length=20),
        ),
    ]
