# Generated by Django 5.2.13 on 2026-08-13 13:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_operational_settings(apps, schema_editor):
    Arena = apps.get_model('arena', 'Arena')
    Settings = apps.get_model('arena', 'ArenaOperationalSettings')
    Settings.objects.bulk_create([
        Settings(
            arena_id=arena.id,
            classes_enabled=True,
            open_access_enabled=False,
            reservations_enabled=True,
            store_enabled=True,
            open_access_validation='reception',
            open_access_pending_minutes=10,
        )
        for arena in Arena.objects.all().only('id')
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0011_arena_checkin_minutes_after_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='tipo_negocio',
            field=models.CharField(choices=[('arena', 'Arena'), ('academia', 'Academia')], db_index=True, default='arena', max_length=20),
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_acessos_dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_acessos_mes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_acessos_semana',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo_acesso',
            field=models.CharField(choices=[('classes_only', 'Aulas'), ('open_access', 'Acesso livre'), ('hybrid', 'Híbrido')], default='classes_only', max_length=20),
        ),
        migrations.AddField(
            model_name='quadra',
            name='tipo_espaco',
            field=models.CharField(choices=[('court', 'Quadra'), ('gym_floor', 'Musculação'), ('martial_arts', 'Lutas'), ('spinning', 'Spinning'), ('pool', 'Piscina'), ('studio', 'Estúdio'), ('functional', 'Funcional'), ('other', 'Outro')], default='court', max_length=30),
        ),
        migrations.CreateModel(
            name='AccessVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Aguardando validação'), ('confirmed', 'Confirmada'), ('rejected', 'Rejeitada'), ('checked_out', 'Encerrada'), ('expired', 'Expirada')], db_index=True, default='pending', max_length=20)),
                ('origem', models.CharField(choices=[('mobile', 'Aplicativo mobile'), ('manual', 'Manual'), ('reception', 'Recepção'), ('turnstile', 'Catraca'), ('integration', 'Integração')], default='mobile', max_length=20)),
                ('solicitado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('entrada_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('saida_em', models.DateTimeField(blank=True, null=True)),
                ('checkout_origem', models.CharField(blank=True, choices=[('member', 'Membro'), ('reception', 'Recepção'), ('automatic', 'Automático'), ('turnstile', 'Catraca'), ('integration', 'Integração')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('inadimplente_no_momento', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_visits', to=settings.AUTH_USER_MODEL)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_visits', to='arena.arena')),
                ('checkout_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_visits_checked_out', to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_visits', to='arena.matricula')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_visits', to='arena.plano')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_visits_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solicitado_em'],
            },
        ),
        migrations.CreateModel(
            name='AccessIntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('visit.confirmed', 'Visita confirmada'), ('visit.rejected', 'Visita rejeitada')], max_length=40)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processado'), ('failed', 'Falhou'), ('ignored', 'Ignorado')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to='arena.accessvisit')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaOperationalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_enabled', models.BooleanField(default=True)),
                ('open_access_enabled', models.BooleanField(default=False)),
                ('reservations_enabled', models.BooleanField(default=True)),
                ('store_enabled', models.BooleanField(default=True)),
                ('open_access_validation', models.CharField(choices=[('reception', 'Validação pela recepção'), ('automatic', 'Automática')], default='reception', max_length=20)),
                ('open_access_pending_minutes', models.PositiveSmallIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arena', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_settings', to='arena.arena')),
            ],
        ),
        migrations.RunPython(backfill_operational_settings, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PlanAccessWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='janelas_acesso', to='arena.plano')),
            ],
            options={
                'ordering': ['weekday', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('bidirectional', 'Bidirecional')], default='entry', max_length=20)),
                ('provider_key', models.SlugField(default='manual')),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('credential_reference', models.CharField(blank=True, max_length=160)),
                ('ativa', models.BooleanField(default=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_points', to='arena.arena')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('arena', 'nome'), name='unique_access_point_name_per_arena')],
            },
        ),
        migrations.AddIndex(
            model_name='accessvisit',
            index=models.Index(fields=['arena', 'status', 'solicitado_em'], name='arena_acces_arena_i_d567f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessvisit',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('arena', 'aluno'), name='unique_open_access_visit_per_member'),
        ),
        migrations.AddConstraint(
            model_name='planaccesswindow',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='plan_access_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='planaccesswindow',
            constraint=models.UniqueConstraint(fields=('plano', 'weekday', 'starts_at', 'ends_at'), name='unique_plan_access_window'),
        ),
    ]
