# Generated by Django 5.2.13 on 2026-07-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='papel',
            field=models.CharField(blank=True, choices=[('dono', 'Dono'), ('recepcao', 'Recepcao'), ('financeiro', 'Financeiro'), ('professor', 'Professor'), ('estoque', 'Estoque'), ('aluno', 'Aluno')], max_length=20),
        ),
    ]
