# Generated by Django 5.2.13 on 2026-07-30 14:20

import common_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/', validators=[common_validators.validate_image_upload]),
        ),
    ]
