# Generated by Django 5.2.13 on 2026-08-11 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_token_version_alter_usuario_papel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_classes', models.BooleanField(default=True)),
                ('app_checkins', models.BooleanField(default=True)),
                ('app_financial', models.BooleanField(default=True)),
                ('app_reservations', models.BooleanField(default=True)),
                ('email_classes', models.BooleanField(default=True)),
                ('email_checkins', models.BooleanField(default=True)),
                ('email_financial', models.BooleanField(default=True)),
                ('email_reservations', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('new_email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'new_email'], name='usuarios_em_user_id_507f95_idx')],
            },
        ),
    ]
